### ISSUE TITLE
Use lwt_log

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/resource-pooling#4]
@jrochel, is there any reason why `resource-pooling` does not depend on this package? This would make `ocsigen-start` compatible with Lwt 4.x (once we make minor releases for Ocsigenserver and Eliom).

I know that the community converges towards the `logs` package, but we are probably not going to migrate all Ocsigen packages any time soon, and having a separate logging infrastructure for `resource-pooling` doesn't help much.

**Comment by jrochel** [comment]
Done: https://github.com/ocsigen/resource-pooling/commit/89e529807680a87f817cdb6cd89649b8f24833a7

**Comment by jrochel** [comment]
Version 0.3.1 will include this commit: https://github.com/ocaml/opam-repository/pull/12494 (and nothing else)
